language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - android-25
  - extra-android-support
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-25
  - sys-img-armeabi-v7a-android-20
sudo: false
script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - ./gradlew assembleRelease
  - name=`ls app/build/outputs/apk/`
  - mv $name app/build/outputs/apk/CodeWars.apk

before_install:
- chmod +x gradlew
- openssl aes-256-cbc -K $encrypted_54c28a617310_key -iv $encrypted_54c28a617310_iv
  -in codewars_juhezi.jks.enc -out codewars_juhezi.jks -d
deploy:
  provider: release
  api_key:
    secure: 2d92c1dbd0e040231e229b300b9221c0c2262a8e
  file: app/build/outputs/apk/CodeWars.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
